# Generated by Django 5.2.13 on 2026-04-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_hashtag_posthashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/'),
        ),
    ]
